### PR TITLE
max_messages from 5000 to 50000

### PR DESCRIPTION
**Pull request by spirellii**
So events happening on the last 50000 messages will be logged instead of only the last 5000

### CODE REVIEW

**Comment by greg6775** [comment]
EZ

**Comment by BaseChip** [comment]
Why?😅

**Comment by spirellii** [comment]
As said above, so events happening on the last 50000 messages will be logged instead of only the last 5000

**Comment by BaseChip** [comment]
I know, but I don't think this bot need it

**Comment by spirellii** [comment]
Yea, but it'd be useful to use this in combination with sharding if the bot reaches a specific amount of servers

**Comment by greg6775** [comment]
Digga ihr könnt auch auf deutsch euch unterhalten

**Comment by spirellii** [comment]
lol

**Comment by greg6775** [comment]
Ja

**Pull request merged**
